# -*- coding: utf-8 -*-
"""diskon.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dJSm6pgAIHV3qDyRAiGFIytBafB4Q3lX
"""

import os
import sys
total = []

def clear_screen():
    os.system('clear' if(os.name=='nt') else 'clear')

def Back():
    print("\n")
    input("tekan enter pada keyboard untuk kembali")
    clear_screen()

def check_out():
    print("--------------------------------")
    print("**    LAKUKAN PEMBAYARAN !    **")
    print("--------------------------------")

def menu_awal():
    while (True):
        print("--------------------------------------")
        print("     Selamat Datang di Mrs.Thrift     ")
        print("--------------------------------------")
        print("**       LAKUKAN PEMBELIAN !        **")
        print("--------------------------------------")
        print(" 1 Sweater                           ")
        print(" 2 Kemeja                            ")
        print(" 3 Celana                            ")
        print(" 4 Rok                               ")
        print(" 5 Daftar Diskon                     ")
        print(" 6 Check Out                         ")
        print(" 7 Back                              ")
        try:
            a=int(input("pilih menu 1-7: "))
            print()
            if(a==1):
                Sweater()
                Back()
            elif(a==2):
                Kemeja()
                Back()
            elif(a==3):
                Celana()
                Back()
            elif(a==4):
                Rok()
                Back()
            elif(a==5):
                daftar_diskon()
                confirm()
                Back()
            elif(a==6):
                check_out()
                akhir()
                break
            elif(a==7):
                Back()
                break
            else:
                print("Masukkan menu 1-7")
                Back()
                continue
        except ValueError:
            print("Masukkan sesuai yang tertera pada daftar menu!")
            Back()
            continue

def Sweater():
    print(" No |        Daftar Barang       |  Harga")
    print("-----------------------------------------")
    print(" 1  | Sweater crew neck          |  45000")
    print(" 2  | Sweater O neck             |  40000")
    print(" 3  | Sweater V neck             |  40000")
    print(" 4  | Sweater Turtleneck         |  50000")
    print("-----------------------------------------")
    kode=int(input("Masukkan nomor barang :  "))
    if(kode==1):
        jumlah1=int(input("Masukkan jumlah barang :  "))
        total1=45000*jumlah1
        total.append(total1)
        tanya()
    elif(kode==2):
        jumlah2=int(input("Masukkan jumlah barang :  "))
        total2=40000*jumlah2
        total.append(total2)
        tanya()
    elif(kode==3):
        jumlah3=int(input("Masukkan jumlah barang :  "))
        total3=40000*jumlah3
        total.append(total3)
        tanya()
    elif(kode==4):
        jumlah4=int(input("Masukkan jumlah barang :  "))
        total4=50000*jumlah4
        total.append(total4)
        tanya()
    return

def Kemeja():
    print(" No |        Daftar Barang       |  Harga")
    print("-----------------------------------------")
    print(" 1  | kemeja blouse              |  25000")
    print(" 2  | kemeja denim               |  35000")
    print(" 3  | kemeja flanel              |  30000")
    print("-----------------------------------------")
    kode=int(input("Masukkan nomor barang :  "))
    if(kode==1):
        jumlah1=int(input("Masukkan jumlah barang :  "))
        total1=25000*jumlah1
        total.append(total1)
        tanya()
    elif(kode==2):
        jumlah2=int(input("Masukkan jumlah barang :  "))
        total2=35000*jumlah2
        total.append(total2)
        tanya()
    elif(kode==3):
        jumlah3=int(input("Masukkan jumlah barang :  "))
        total3=30000*jumlah3
        total.append(total3)
        tanya()
    return

def Celana():
    print(" No |        Daftar Barang       |  Harga")
    print("-----------------------------------------")
    print(" 1  | celana kain                |  25000")
    print(" 2  | celana jeans               |  30000")
    print(" 3  | overall                    |  40000")
    print("-----------------------------------------")
    kode=int(input("Masukkan nomor barang :  "))
    if(kode==1):
        jumlah1=int(input("Masukkan jumlah barang :  "))
        total1=25000*jumlah1
        total.append(total1)
        tanya()
    elif(kode==2):
        jumlah2=int(input("Masukkan jumlah barang :  "))
        total2=30000*jumlah2
        total.append(total2)
        tanya()
    elif(kode==3):
        jumlah3=int(input("Masukkan jumlah barang :  "))
        total3=40000*jumlah3
        total.append(total3)
        tanya()
    return

def Rok():
    print(" No |        Daftar Barang       |  Harga")
    print("-----------------------------------------")
    print(" 1  | rok kain                   |  15000")
    print(" 2  | rok jeans/denim            |  20000")
    print(" 3  | rok tutu                   |  25000")
    print("-----------------------------------------")
    kode=int(input("Masukkan nomor barang :  "))
    if(kode==1):
        jumlah1=int(input("Masukkan jumlah barang :  "))
        total1=15000*jumlah1
        total.append(total1)
        tanya()
    elif(kode==2):
        jumlah2=int(input("Masukkan jumlah barang :  "))
        total2=20000*jumlah2
        total.append(total2)
        tanya()
    elif(kode==3):
        jumlah3=int(input("Masukkan jumlah barang :  "))
        total3=25000*jumlah3
        total.append(total3)
        tanya()
    return

def daftar_diskon():
    print(" No |      Total Belanja       | Daftar Diskon ")
    print("-----------------------------------------------")
    print(" 1  | > Rp 50000,-             |      2%       ")
    print(" 2  | > Rp 100000,-            |      5%       ")
    print(" 3  | > Rp 300000,-            |      7%       ")
    print(" 4  | > Rp 500000,-            |      10%      ")
    print(" 5  | > Rp 1000000,-           |      15%      ")
    print("-----------------------------------------------")

def tanya():
    print("\n---------------------------------------------------")
    tanya = input("apakah Anda ingin menambah barang? [y/t] : ")
    print("-----------------------------------------------------")
    if(tanya=="y"):
        menu_awal()
    elif(tanya=="t"):
        confirm()
    else:
        print("Pilihan yang Anda masukan salah!")
        
def confirm():
    print("\n------------------------------------------------")
    confirm = input("apakah barang Anda sudah benar? [y/t] : ")
    print("--------------------------------------------------")
    if(confirm=="y"):
        akhir()
    else:
        Back()
       # print("Pilihan yang Anda masukan salah!")

def akhir():
    for harga in total:
        print("SubTotal           : ", sum(total))
        diskon=0
        a=sum(total)
        if(a>1000000):
            diskon=a*15/100
        elif(a>500000):
            diskon=a*10/100
        elif(a>300000):
            diskon=a*7/100
        elif(a>100000):
            diskon=a*5/100
        elif(a>50000):
            diskon=a*2/100
        else:
            diskon=0
        print("Potongan Harga    : ", diskon)
        totalakhir=a-diskon
        print("Total             : ", totalakhir)
        print("--------------------------------")
        bayar=int(input("Jumlah Pembayaran :   "))
        kembalian=bayar-totalakhir
        print("Kembalian         : ", kembalian)
        print("--------------------------------------------")
        print(" Terimakasih Telah Berkunjung di Mrs.Thrift ")
        print("--------------------------------------------")
        break
menu_awal()

