print('-'*35)
print('Tugas 1 SISOP Kelas-A')
print('-'*35)
print('Nama : Edelin Fortuna')
print('NPM : 21083010087')
print('-'*35)
print('notes :')
print('-'*35)
print('Halo Dunia!')
print('Ini adalah skrip Bash Pertamaku di Linux')
